language: cpp
addons:
  apt:
    sources:
        # Clang 3.8
        - llvm-toolchain-precise-3.8
        # Newer GCC
        - ubuntu-toolchain-r-test
    packages:
        - check
        - libboost-dev
        - libreadline-dev
        - libpam0g-dev
        - libssl-dev
        - libhwloc-dev
        - libxml2-dev
        - libcr-dev
        - clang-3.8
        - gcc-5
        - g++-5

compiler:
  - clang
  - gcc

script:
    - ./autogen.sh
    - ./configure --with-check
    - make
    - make check -k
    - make distcheck
