language: cpp
addons:
  apt:
    sources:
        # Clang 3.7
        - llvm-toolchain-precise-3.7
        # Newer GCC
        - ubuntu-toolchain-r-test
    packages:
        - check

compiler:
  - clang
  - gcc

script:
    - ./autogen.sh
    - ./configure --with-check
    - make
    - make check -k
    - make distcheck
