language: cpp
addons:
  apt:
    packages:
        - check
        - libboost-dev
        - libreadline-dev
        - libpam0g-dev
        - libssl-dev
        - libhwloc-dev
        - libxml2-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - OUR_CC=gcc OUR_CXX=g++

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8', 'g++-4.8']
      env:
        - OUR_CC=gcc-4.8 OUR_CXX=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.9', 'g++-4.9']
      env:
        - OUR_CC=gcc-4.9 OUR_CXX=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5', 'g++-5']
      env:
        - OUR_CC=gcc-5 OUR_CXX=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-6', 'g++-6']
      env:
        - OUR_CC=gcc-6 OUR_CXX=g++-6

install:
    - ./autogen.sh
    - CC=$OUR_CC CXX=$OUR_CXX ./configure --with-check --enable-acct-x --enable-drmaa --enable-pam --enable-cgroups
    - make -j2

script:
    - make check -k
    - make distcheck
