language: cpp
addons:
  apt:
    packages: &general
        - check
        - libboost-dev
        - libreadline-dev
        - libpam0g-dev
        - libssl-dev
        - libhwloc-dev
        - libxml2-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: [*general]
      env:
        - OUR_CC=gcc OUR_CXX=g++

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [*general, 'gcc-4.8', 'g++-4.8']
      env:
        - OUR_CC=gcc-4.8 OUR_CXX=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [*general, 'gcc-4.9', 'g++-4.9']
      env:
        - OUR_CC=gcc-4.9 OUR_CXX=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [*general, 'gcc-5', 'g++-5']
      env:
        - OUR_CC=gcc-5 OUR_CXX=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [*general, 'gcc-6', 'g++-6']
      env:
        - OUR_CC=gcc-6 OUR_CXX=g++-6

install:
    - wget -q -O hwloc.tar.gz https://github.com/open-mpi/hwloc/archive/hwloc-1.11.4.tar.gz
    - tar -xzf hwloc.tar.gz
    - mkdir $HOME/opt
    - pushd hwloc-*/ && ./autogen.sh && ./configure --prefix=$HOME/opt && make && make install && popd
    - export PKG_CONFIG_PATH=$HOME/opt/lib/pkgconfig:$PKG_CONFIG_PATH
    - export LD_LIBRARY_PATH=$HOME/opt/lib:$LD_LIBRARY_PATH
    - pkg-config --print-errors --cflags --libs "hwloc >= 1.9"

script:
    - ./autogen.sh
    - CC=$OUR_CC CXX=$OUR_CXX ./configure --with-check --with-pam --enable-acct-x --enable-drmaa --enable-cgroups
    - make -j2
    - make check -k
    - make distcheck

after_failure:
    - set
    - cat config.log
